// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpqlemhhrewrxojoqvph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwcWxlbWhocmV3cnhvam9xdnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjgzNzMsImV4cCI6MjA3MTgwNDM3M30.aYpJ_x46RC0BT8cN0h7ecKAc6xgyW-67PanS8zxh8Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});